services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

#  api:
#    build:
#      dockerfile: Dockerfile.development
#    ports:
#      - '8000:8000'
#    env_file:
#      - ./.env
#    volumes:
#      - ./src:/app/src
volumes:
  my-db:
